Repository GetStream/stream-chat-swiftui, pull requests merged in 2024-06, with the labels that each got.

#497 Update release flow to be able to start the release from CI
  .github/actions/bootstrap/action.yml
  .github/actions/xcode-cache/action.yml
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/start-new-release.yml
  Gemfile.lock
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#499 Fix TestOps API request failure
  Gemfile.lock
  fastlane/Allurefile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#503 Add source tag to podspec
  StreamChatSwiftUI-XCFramework.podspec
  StreamChatSwiftUI.podspec
Labels: 🤖 CI/CD

#511 Return pods
  fastlane/Fastfile
Labels: 🤖 CI/CD

#513 Dismiss keyboard when tapping on the empty message list
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChannelInfo/ChatChannelInfoView.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift
  Sources/StreamChatSwiftUI/Utils/KeyboardHandling.swift
  StreamChatSwiftUITestsAppTests/Pages/MessageListPage.swift
  StreamChatSwiftUITestsAppTests/Robots/UserRobot.swift
  StreamChatSwiftUITestsAppTests/Tests/MessageList_Tests.swift
Labels: bug, swiftui-repo

#520 Add a new build configuration for profiling
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  StreamChatSwiftUI.xcodeproj/xcshareddata/xcschemes/DemoAppSwiftUI.xcscheme
Labels: swiftui-repo

#504 Add inline error message banners for polls
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelView.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollAllOptionsView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollAttachmentView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollAttachmentViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollCommentsView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollCommentsViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollOptionAllVotesView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollOptionAllVotesViewModel.swift
  Sources/StreamChatSwiftUI/CommonViews/AlertBannerViewModifier.swift
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  StreamChatSwiftUITests/Tests/CommonViews/AlertBannerViewModifier_Tests.swift
  StreamChatSwiftUITests/Tests/CommonViews/__Snapshots__/AlertBannerViewModifier_Tests/test_alertBanner_snapshot.1.png
Labels: enhancement, swiftui-repo, ✅ QAed

#523 Introducing develop branch
  .github/workflows/publish-release.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD

#525 Grouping image and video attachments in the same message
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChannelInfo/MediaAttachmentsView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Gallery/GalleryView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Gallery/GridPhotosView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/ImageAttachmentView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/QuotedMessageView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/VideoAttachmentView.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageView_Tests/test_messageViewImage_snapshot3ImagesAndVideo.1.png
Labels: ✅ QAed

#530 [CI] Update iOS runtimes' download
  .github/actions/setup-ios-runtime/action.yml
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .gitignore
  Scripts/bootstrap.sh
  Scripts/install_ios_runtime.sh
  fastlane/.env
  fastlane/Fastfile
Labels: 🤖 CI/CD

#522 Improve list updates
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageIdBuilder.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Reactions/MessageActions/DefaultMessageActions.swift
  Sources/StreamChatSwiftUI/StreamChat.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChatMessageIDs_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/Base TestCase/StreamTestCase.swift
Labels: swiftui-repo
