Repository GetStream/stream-chat-swiftui, pull requests merged in 2024-07, with the labels that each got.

#535 Skip pod lint when targeting a branch for stream-chat-swift
  fastlane/Fastfile
Labels: 🤖 CI/CD

#534 Jumping to an unread message did not keep scroll location
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift
Labels: bug, swiftui-repo, ✅ QAed

#537 CI adjustments
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#536 Editing quoted messages did not refresh the message list
  Sources/StreamChatSwiftUI/Utils/MessageCachingUtils.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageCachingUtils_Tests.swift
Labels: bug, swiftui-repo

#540 Disable caching for author in message list
  CHANGELOG.md
  Sources/StreamChatSwiftUI/Utils/MessageCachingUtils.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageCachingUtils_Tests.swift
Labels: bug, swiftui-repo

#529 [CI] Add merge main to develop lane
  fastlane/Fastfile
Labels: 🤖 CI/CD

#549 Remove StreamChat module's shadow at xcframeworks' swiftinterfaces
  fastlane/Fastfile
Labels: 🤖 CI/CD

#555 [CI] Automate merge to develop on release
  .github/workflows/publish-release.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD

#560 [CI] Comment SDK size on every commit
  .github/workflows/sdk-size-metrics.yml
  .github/workflows/smoke-checks.yml
  .gitignore
  fastlane/Fastfile
  fastlane/sdk_size_export_options.plist
Labels: 🤖 CI/CD

#562 [CI] Automatically update SDK size badge in README.md
  README.md
  fastlane/Fastfile
Labels: 🤖 CI/CD

#563 [CI] Adjust sdk size report on release PRs
  .github/workflows/sdk-size-metrics.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD

#567 [CI] Correctly retrieve a git branch on CI
  .github/workflows/cron-checks.yml
  .github/workflows/publish-release.yml
  .github/workflows/sdk-size-metrics.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/start-new-release.yml
  fastlane/Allurefile
  fastlane/Fastfile
  fastlane/Sonarfile
Labels: 🤖 CI/CD

#566 [CI] Do not cache SPM due to GitHub cache-related issues
  .github/actions/xcode-cache/action.yml
Labels: 🤖 CI/CD

#569 [CI] Update merge main to develop lane
  fastlane/Fastfile
Labels: 🤖 CI/CD
