Repository GetStream/stream-chat-swiftui, pull requests merged in 2024-11, with the labels that each got.

#636 [CI] Fix E2E tests
  StreamChatSwiftUITestsAppTests/Tests/MessageList_Tests.swift
Labels: 🤖 CI/CD

#639 Fix Channel List stuck in Empty View State in rare conditions
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListViewModel.swift
Labels: bug

#645 [CI] Fix failing test
  StreamChatSwiftUITestsAppTests/Robots/UserRobot+Asserts.swift
Labels: 🤖 CI/CD

#652 [CI] Add snapshot version postfix
  Gemfile.lock
  Sources/StreamChatSwiftUI/Generated/SystemEnvironment+Version.swift
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#663 Fix accessing messages with invalid index
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelViewModel_Tests.swift
Labels: bug, swiftui-repo

#666 [CI] Fix TestFlight app version
  fastlane/Fastfile
Labels: 🤖 CI/CD

#669 Do not show giphy in channel's preview message
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListItem.swift
  StreamChatSwiftUITests/Tests/ChatChannelList/ChatChannelListItemView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannelList/__Snapshots__/ChatChannelListItemView_Tests/test_channelListItem_giphyMessage.1.png
  StreamChatSwiftUITests/Tests/ChatChannelList/__Snapshots__/ChatChannelListItemView_Tests/test_channelListItem_giphyMessageLatestButPreviewIsAnotherMessage.1.png
Labels: bug, ✅ QAed
