Repository GetStream/stream-chat-swiftui, pull requests merged in 2024-09, with the labels that each got.

#596 [CI] Clean up disk space on CI before downloading iOS runtimes
  .github/actions/setup-ios-runtime/action.yml
Labels: 🤖 CI/CD

#593 Channel was sometimes marked as read on open
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift
  Sources/StreamChatSwiftUI/CommonViews/DelayedRenderingViewModifier.swift
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelViewDateOverlay_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageListViewAvatars_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageListViewLastGroupHeader_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageListViewNewMessages_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageListView_Tests.swift
Labels: bug, swiftui-repo, ✅ QAed

#597 [CI] Update git fetch-depth on release
  .github/workflows/release-publish.yml
Labels: 🤖 CI/CD

#600 Jump to first unread message button in the message list was not possible to close in some cases
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift
Labels: bug

#607 Reduce view updates when computing frame for long press action
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageContainerView.swift
Labels: bug

#609 ChatChannelListView navigation did not trigger when using a custom container
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListView.swift
Labels: bug, swiftui-repo, 🤞 Ready for QA

#610 Channel was sometimes not marked as read when tapping the x on the unread message pill
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift
Labels: bug, swiftui-repo

#613 [CI] Improvements
  .github/workflows/release-publish.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD
