Repository GetStream/stream-chat-swiftui, pull requests merged in 2024-10, with the labels that each got.

#616 Updated StreamChat dependency to 4.64.0
  Package.swift
  StreamChatSwiftUI-XCFramework.podspec
  StreamChatSwiftUI.podspec
  StreamChatSwiftUI.xcodeproj/project.pbxproj
Labels: dependencies

#611 Channel was sometimes not selected when setting selectedChannelId
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListViewModel.swift
  StreamChatSwiftUITests/Infrastructure/Shared/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
  StreamChatSwiftUITests/Tests/ChatChannelList/ChatChannelListViewModel_Tests.swift
Labels: bug, swiftui-repo

#619 [CI] Bump gem versions
  Gemfile.lock
Labels: 🤖 CI/CD

#618 Make ChatChannelScreen init public
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelScreen.swift
Labels: documentation

#627 Fix crash when opening message overlay in iPad with a TabBar
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/Reactions/ReactionsOverlayView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Utils/ChatChannelHelpers.swift
  Sources/StreamChatSwiftUI/Utils/SnapshotCreator.swift
Labels: bug

#631 [CI] Implement Testflight Workflow
  .github/workflows/testflight.yml
  Gemfile.lock
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/testflight_export_options.plist
Labels: 🤖 CI/CD
