Repository GetStream/stream-chat-swiftui, pull requests merged in 2025-09, with the labels that each got.

#939 Add navigationBarTitle, navigationBarSubtitle, navigationBarTintColor, navigationBarBackground to ColorPalette
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChannelHeader/ChatChannelHeaderViewModifier.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChannelHeader/MessageThreadHeaderViewModifier.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChannelInfo/ChatChannelInfoView.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChannelInfo/FileAttachmentsView.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChannelInfo/MediaAttachmentsView.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChannelInfo/PinnedMessagesView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/FileAttachmentPreview.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollAllOptionsView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollCommentsView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollOptionAllVotesView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollResultsView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Polls/CreatePollView.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListHeader.swift
  Sources/StreamChatSwiftUI/ChatChannelList/MoreChannelActionsFullScreenWrappingView.swift
  Sources/StreamChatSwiftUI/ChatThreadList/ChatThreadListHeaderViewModifier.swift
  Sources/StreamChatSwiftUI/ColorPalette.swift
  Sources/StreamChatSwiftUI/CommonViews/NavigationBarBackgroundViewModifier.swift
  Sources/StreamChatSwiftUI/Utils/NavigationContainerView.swift
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/ChatChannelInfoView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/FileAttachmentPreview_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/ChatChannelInfoView_Tests/test_chatChannelInfoView_navigationBarAppearance.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/FileAttachmentPreview_Tests/test_fileAttachmentPreview_navigationBarAppearance.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/FileAttachmentPreview_Tests/test_fileAttachmentPreview_pdf.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/CreatePollView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/ChatChannelHeader_Tests/test_channelTitleView_theme_snapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/ChatChannelView_Tests/test_chatChannelView_customizedNavigationBar_snapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/CreatePollView_Tests/test_createPollView_customizedNavigationBarSnapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannelList/ChatChannelListView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannelList/__Snapshots__/ChatChannelListView_Tests/test_channelListView_customizedNavigationBar.1.png
  StreamChatSwiftUITests/Tests/StreamChatTestCase.swift
Labels: ✅ QAed, ✅ Feature

#958 Fix message list not scrolling to newest message with long text
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelViewModel_Tests.swift
Labels: ✅ QAed

#973 [CI] Update swift format lane to check for foundation import
  fastlane/Fastfile
Labels: 🤖 CI/CD

#981 [CI] Remove CocoaPods
  .github/workflows/cron-checks.yml
  .github/workflows/release-publish.yml
  .github/workflows/smoke-checks.yml
  .gitignore
  AGENTS.md
  Gemfile
  Gemfile.lock
  Sources/StreamChatSwiftUI/README.md
  Sources/StreamChatSwiftUI/Utils/BundleExtensions.swift
  Sources/StreamChatSwiftUI/Utils/LazyImageExtensions.swift
  StreamChatSwiftUI-XCFramework.podspec
  StreamChatSwiftUI.podspec
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: 🤖 CI/CD
