Repository GetStream/stream-chat-swiftui, pull requests merged in 2025-03, with the labels that each got.

#771 [CI] Bump Xcode, macOS and iOS versions
  .github/workflows/cron-checks.yml
  .github/workflows/release-merge.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-start.yml
  .github/workflows/sdk-size-metrics.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/testflight.yml
  .github/workflows/update-copyright.yml
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/FileAttachmentsView_Tests/test_fileAttachmentsView_emptySnapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/MediaAttachmentsView_Tests/test_mediaAttachmentsView_emptySnapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/PinnedMessagesView_Tests/test_pinnedMessagesView_emptySnapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/GalleryView_Tests/test_galleryView_snapshotLoading.1.png
  StreamChatSwiftUITests/Tests/ChatChannelList/__Snapshots__/NoChannelsView_Tests/test_noChannelsView_snapshot.1.png
  fastlane/Fastfile
Labels: 🤖 CI/CD

#782 Use the same template as the UIKit repository
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🤖 CI/CD

#776 Show translated text for participant messages
  CHANGELOG.md
  DemoAppSwiftUI/AppConfiguration/AppConfiguration.swift
  DemoAppSwiftUI/AppConfiguration/AppConfigurationTranslationView.swift
  DemoAppSwiftUI/AppConfiguration/AppConfigurationView.swift
  DemoAppSwiftUI/AppDelegate.swift
  DemoAppSwiftUI/LoginView.swift
  DemoAppSwiftUI/LoginViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChannelInfo/PinnedMessagesView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/MessageComposerView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageContainerView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/QuotedMessageView.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListItem.swift
  Sources/StreamChatSwiftUI/ChatChannelList/SearchResultsView.swift
  Sources/StreamChatSwiftUI/ChatThreadList/ChatThreadListItem.swift
  Sources/StreamChatSwiftUI/Generated/L10n.swift
  Sources/StreamChatSwiftUI/Resources/en.lproj/Localizable.strings
  Sources/StreamChatSwiftUI/Utils/Common/ChatMessage+Extensions.swift
  Sources/StreamChatSwiftUI/Utils/MessagePreviewFormatter.swift
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  StreamChatSwiftUITests/Tests/ChatChannel/MessageComposerView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageContainerView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerQuotedMessage_translated.default-dark.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerQuotedMessage_translated.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageContainerView_Tests/test_translatedText_myMessageIsNotTranslated_snapshot.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageContainerView_Tests/test_translatedText_myMessageIsNotTranslated_snapshot.extraExtraExtraLarge-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageContainerView_Tests/test_translatedText_myMessageIsNotTranslated_snapshot.rightToLeftLayout-default.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageContainerView_Tests/test_translatedText_myMessageIsNotTranslated_snapshot.small-dark.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageContainerView_Tests/test_translatedText_participant_snapshot.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageContainerView_Tests/test_translatedText_participant_snapshot.extraExtraExtraLarge-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageContainerView_Tests/test_translatedText_participant_snapshot.rightToLeftLayout-default.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageContainerView_Tests/test_translatedText_participant_snapshot.small-dark.png
  StreamChatSwiftUITests/Tests/ChatChannelList/ChatChannelListItemView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannelList/__Snapshots__/ChatChannelListItemView_Tests/test_channelListItem_translatedText_me.1.png
  StreamChatSwiftUITests/Tests/ChatChannelList/__Snapshots__/ChatChannelListItemView_Tests/test_channelListItem_translatedText_participant.1.png
  StreamChatSwiftUITests/Tests/Utils/ChatMessageExtensions_Tests.swift
Labels: ✅ QAed, ✅ Feature

#781 Show typing suggestions for text with whitespace
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/Composer/Suggestions/TypingSuggester.swift
  StreamChatSwiftUITests/Tests/ChatChannel/Suggestions/TypingSuggester_Tests.swift
Labels: ✅ QAed, 🐞 Bug

#783 [CI] Downgrade Xcode version for E2E tests
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#785 [CI] Resolve E2E tests issue on CI
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  StreamChatSwiftUITestsAppTests/Tests/Attachments_Tests.swift
Labels: 🤖 CI/CD

#775 Add Draft Messages Support
  CHANGELOG.md
  DemoAppSwiftUI/AppDelegate.swift
  DemoAppSwiftUI/AppleMessageComposerView.swift
  DemoAppSwiftUI/PinChannelHelpers.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/ComposerModels.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/MessageComposerView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/MessageComposerViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/Suggestions/InstantCommands/GiphyCommandHandler.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/Suggestions/InstantCommands/TwoStepMentionCommand.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListConfig.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListItem.swift
  Sources/StreamChatSwiftUI/ChatThreadList/ChatThreadListItem.swift
  Sources/StreamChatSwiftUI/Generated/L10n.swift
  Sources/StreamChatSwiftUI/Resources/en.lproj/Localizable.strings
  Sources/StreamChatSwiftUI/ViewModelsFactory.swift
  StreamChatSwiftUITests/Infrastructure/Mocks/ChatMessageControllerSUI_Mock.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelDataSource_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageComposerViewModel_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageComposerView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_draftWithCommand.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_draftWithFileAttachment.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_draftWithImageAttachment.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_draftWithVideoAttachment.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_draftWithVoiceRecordingAttachment.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannelList/ChatChannelListItemView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannelList/__Snapshots__/ChatChannelListItemView_Tests/test_channelListItem_draftMessage.1.png
  StreamChatSwiftUITests/Tests/ChatChannelList/__Snapshots__/ChatChannelListItemView_Tests/test_channelListItem_draftMessageWithAttachment.1.png
  StreamChatSwiftUITests/Tests/ChatThreadList/ChatThreadListItemView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatThreadList/__Snapshots__/ChatThreadListItemView_Tests/test_threadListItem_whenDraftMessage.1.png
  StreamChatSwiftUITests/Tests/ChatThreadList/__Snapshots__/ChatThreadListItemView_Tests/test_threadListItem_whenDraftMessageHasAttachment.1.png
Labels: ✅ Feature, 🧪 QAing

#789 [CI] Remove all the SwiftUICore module shadows in xcframeworks
  fastlane/Fastfile
Labels: 🤖 CI/CD, ✅ QAed
