Repository GetStream/stream-chat-swiftui, pull requests merged in 2025-01, with the labels that each got.

#702 Use bright color for typing indicator in dark mode
  CHANGELOG.md
  Sources/StreamChatSwiftUI/CommonViews/TypingIndicatorView.swift
  StreamChatSwiftUITests/Tests/ChatChannel/TypingIndicatorView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/TypingIndicatorView_Tests/test_typingIndicatorView_snapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/TypingIndicatorView_Tests/test_typingIndicatorView_snapshot.default-dark.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/TypingIndicatorView_Tests/test_typingIndicatorView_snapshot.default-light.png
Labels: bug, swiftui-repo

#707 [CI] Bump macos version on PRs
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#705 Quoted message preview did not update when the quoted message was deleted
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListHelperViews.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/QuotedMessageView.swift
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  StreamChatSwiftUITests/Infrastructure/TestTools/ViewFrameUtils.swift
  StreamChatSwiftUITests/Tests/ChatChannel/QuotedMessageView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/QuotedMessageView_Tests/test_quotedMessageView_deletedSnapshot.default-dark.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/QuotedMessageView_Tests/test_quotedMessageView_deletedSnapshot.default-light.png
Labels: ✅ QAed

#709 Resolve cron checks CI issue
  .github/workflows/cron-checks.yml
Labels: 🤖 CI/CD

#713 Use AppSettings.fileUploadConfig for setting supported UTI types for the file picker
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/Composer/FilePickerView.swift
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  StreamChatSwiftUITests/Tests/ChatChannel/FilePickerView_Tests.swift
Labels: ✅ QAed

#719 [CI] Bump minimum Xcode version on CI
  .github/workflows/cron-checks.yml
  .github/workflows/release-start.yml
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#718 Remove internal _isDatabaseObserverItemReusingEnabled check
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/AsyncVoiceMessages/VoiceRecordingContainerView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/FileAttachmentView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/GiphyAttachmentView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/ImageAttachmentView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/LinkAttachmentView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageContainerView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageIdBuilder.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListHelperViews.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/QuotedMessageView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/VideoAttachmentView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Reactions/ReactionsOverlayView.swift
  Sources/StreamChatSwiftUI/Utils/MessageCachingUtils.swift
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  StreamChatSwiftUITests/Tests/ChatChannel/ChatMessageIDs_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageCachingUtils_Tests.swift
Labels: swiftui-repo

#728 [CI] Do not build demo app on Xcode 15
  .github/workflows/cron-checks.yml
Labels: 🤖 CI/CD

#731 Show pinned channels at the top in the demo app
  DemoAppSwiftUI/ChannelHeader/ChannelListQueryIdentifier.swift
  DemoAppSwiftUI/DemoAppSwiftUIApp.swift
Labels: 🪧 Demo App

#739 [CI] Lock sonar scanner and mint versions and get rid of brew
  .github/actions/bootstrap/action.yml
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks-swiftui.yml
  .github/workflows/smoke-checks.yml
  .gitignore
  Brewfile
  Brewfile.lock.json
  Githubfile
  Scripts/bootstrap.sh
  fastlane/Sonarfile
Labels: 🤖 CI/CD
