Repository GetStream/stream-chat-swiftui, pull requests merged in 2025-07, with the labels that each got.

#870 Fix channel view tab bar not hidden on iOS 16.0
  CHANGELOG.md
  DemoAppSwiftUI/ChannelHeader/NewChatView.swift
  DemoAppSwiftUI/PinChannelHelpers.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelNavigatableListItem.swift
  Sources/StreamChatSwiftUI/DefaultViewFactory.swift
Labels: ✅ QAed

#877 Implement ruby cache on sonar upload
  .github/workflows/sonar.yml
Labels: 🤖 CI/CD

#883 [CI] Fix Sonar scanner on develop
  .github/workflows/sonar.yml
Labels: 🤖 CI/CD

#889 [CI] Speed up githooks
  lefthook.yml
Labels: 🤖 CI/CD

#890 [CI] Update TestFlight manual upload detection
  fastlane/Fastfile
Labels: 🤖 CI/CD

#893 Remove Xcode 26 workaround which was fixed in beta 4
  DemoAppSwiftUI/AppDelegate.swift
Labels: 🪧 Demo App
