Repository GetStream/stream-chat-swiftui, pull requests merged in 2025-10, with the labels that each got.

#987 Use explicit set of rules in SwiftFormat and SwiftLint and bump versions
  .swiftformat
  .swiftlint.yml
  DemoAppSwiftUI/ChannelHeader/CustomChannelHeader.swift
  Githubfile
  Sources/StreamChatSwiftUI/ChatChannel/ChannelHeader/ChatChannelHeaderViewModifier.swift
  Sources/StreamChatSwiftUI/ChatChannel/Gallery/ShareButtonView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/AsyncVoiceMessages/VoiceRecordingContainerView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/Polls/PollCommentsView.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelSwipeableListItem.swift
  Sources/StreamChatSwiftUI/CommonViews/NavigationBarThemeViewModifier.swift
  Sources/StreamChatSwiftUI/Utils/Common/InputTextView.swift
  Sources/StreamChatSwiftUI/Utils/Common/NukeImageProcessor.swift
  Sources/StreamChatSwiftUI/Utils/Common/VideoPreviewLoader.swift
  StreamChatSwiftUITests/Infrastructure/Shared/CustomAssertions/AssertAsync.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/ChannelInfoMockUtils.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/ChatChannelInfoView_Tests/test_chatChannelInfoView_participantSelectedBasicActionsSnapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/ChatChannelInfoView_Tests/test_chatChannelInfoView_participantSelectedOfflineUserSnapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/ChatChannelInfoView_Tests/test_chatChannelInfoView_participantSelectedWithMuteActionsSnapshot.1.png
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/__Snapshots__/ChatChannelInfoView_Tests/test_chatChannelInfoView_participantSelectedWithRemoveActionSnapshot.1.png
Labels: 🤖 CI/CD

#989 Fix multiple issues around mark unread and unread banner
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelDataSource.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/Reactions/MessageActions/MessageActionsResolver.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelDataSource_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelViewModel_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageActions_Tests.swift
Labels: ✅ QAed

#994 [CI] Get the correct target branch on public interface validation
  fastlane/Fastfile
Labels: 🤖 CI/CD

#984 [V5] Use MainActor in StreamChat, Images, Fonts, Appearance, Utils
  Sources/StreamChatSwiftUI/Appearance.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChannelControllerFactory.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChannelInfo/MediaAttachmentsViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/MessageComposerViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/PhotoAssetsUtils.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/ImageAttachmentView.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageBubble.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListConfig.swift
  Sources/StreamChatSwiftUI/ChatChannel/Utils/ChatChannelExtensions.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChannelAvatarsMerger.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChannelHeaderLoader.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelList.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListItem.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListView.swift
  Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelListViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannelList/SearchResultsView.swift
  Sources/StreamChatSwiftUI/ChatThreadList/ChatThreadListItem.swift
  Sources/StreamChatSwiftUI/ColorPalette.swift
  Sources/StreamChatSwiftUI/DependencyInjection.swift
  Sources/StreamChatSwiftUI/Fonts.swift
  Sources/StreamChatSwiftUI/Generated/L10n.swift
  Sources/StreamChatSwiftUI/Generated/L10n_template.stencil
  Sources/StreamChatSwiftUI/Images.swift
  Sources/StreamChatSwiftUI/StreamChat.swift
  Sources/StreamChatSwiftUI/Utils.swift
  Sources/StreamChatSwiftUI/Utils/Common/ChatMessage+Extensions.swift
  Sources/StreamChatSwiftUI/Utils/Common/ImageMerger.swift
  Sources/StreamChatSwiftUI/Utils/Common/InputTextView.swift
  Sources/StreamChatSwiftUI/Utils/Common/MessageRelativeDateFormatter.swift
  Sources/StreamChatSwiftUI/Utils/Common/NukeImageProcessor.swift
  Sources/StreamChatSwiftUI/Utils/Common/VideoPreviewLoader.swift
  Sources/StreamChatSwiftUI/Utils/MarkdownFormatter.swift
  Sources/StreamChatSwiftUI/Utils/MessagePreviewFormatter.swift
  Sources/StreamChatSwiftUI/Utils/SnapshotCreator.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChannelInfo/PinnedMessagesView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannelList/ChannelAvatarsMerger_Tests.swift
  StreamChatSwiftUITests/Tests/StreamChatTestCase.swift
  StreamChatSwiftUITestsApp/CustomChannelHeader.swift
Labels: ✅ Feature, 💥 Breaking Changes

#1002 Adjust linter rules and linted paths
  .swiftformat
  .swiftlint.yml
  Scripts/GenerateSPMFileLists.swift
  StreamChatSwiftUITestsApp/AppDelegate.swift
  StreamChatSwiftUITestsApp/CustomChannelHeader.swift
  StreamChatSwiftUITestsApp/InternetConnectionMonitor_Mock.swift
  StreamChatSwiftUITestsApp/StartPage.swift
  StreamChatSwiftUITestsApp/StreamChatSwiftUITestsAppApp.swift
  StreamChatSwiftUITestsApp/StreamChatWrapper.swift
  StreamChatSwiftUITestsApp/UserCredentials.swift
  StreamChatSwiftUITestsAppTests/Pages/ChannelListPage.swift
  StreamChatSwiftUITestsAppTests/Pages/MessageListPage.swift
  StreamChatSwiftUITestsAppTests/Pages/SpringBoard.swift
  StreamChatSwiftUITestsAppTests/Pages/ThreadPage.swift
  StreamChatSwiftUITestsAppTests/Robots/UserRobot+Asserts.swift
  StreamChatSwiftUITestsAppTests/Robots/UserRobot.swift
  StreamChatSwiftUITestsAppTests/StreamChatSwiftUITests.swift
  StreamChatSwiftUITestsAppTests/Tests/Attachments_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/Base TestCase/StreamTestCase.swift
  StreamChatSwiftUITestsAppTests/Tests/ChannelList_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/Ephemeral_Messages_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/Message Delivery Status/MessageDeliveryStatus+ChannelList_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/MessageList_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/PushNotification_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/QuotedReply_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/Reactions_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/SlowMode_Tests.swift
  StreamChatSwiftUITestsAppTests/Tests/StreamTestCase+Tags.swift
  fastlane/Fastfile
  lefthook.yml
Labels: 🤖 CI/CD
