Repository GetStream/stream-chat-swiftui, pull requests merged in 2025-06, with the labels that each got.

#846 Keep new messages separator visible when the channel is open
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelViewModel_Tests.swift
Labels: ✅ QAed, 🐞 Bug

#855 [CI] Bump snapshot version after every release
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#858 Fix crash in ChannelAvatarsMerger when accessing shared properties
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannelList/ChannelAvatarsMerger.swift
  StreamChatSwiftUI.xcodeproj/project.pbxproj
  StreamChatSwiftUITests/Tests/ChatChannelList/ChannelAvatarsMerger_Tests.swift
Labels: 🐞 Bug

#862 [CI] Fix Sonar issue on develop
  .github/workflows/sonar.yml
Labels: 🤖 CI/CD
