Repository GetStream/stream-chat-swiftui, pull requests merged in 2025-05, with the labels that each got.

#821 [CI] Update TestFlight app version on manual uploading
  .github/workflows/testflight.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#823 Fix mark unread action not removed when read events are disabled
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/Reactions/MessageActions/DefaultMessageActions.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageActionsViewModel_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageActions_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ReactionsOverlayView_Tests.swift
Labels: 🐞 Bug

#827 [CI] Get rid of jazzy
  Gemfile
  Gemfile.lock
Labels: 🤖 CI/CD

#834 [CI] Resolve formatting issue
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageContainerView.swift
Labels: 🤖 CI/CD

#835 Check canUpdateAnyMessage and canUpdateOwnMessage permissions for edit message action
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/Reactions/MessageActions/DefaultMessageActions.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageActions_Tests.swift
Labels: 🐞 Bug

#837 Add view factory methods for customising headers in GalleryView and VideoPlayerView
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/Gallery/GalleryView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Gallery/VideoPlayerView.swift
  Sources/StreamChatSwiftUI/DefaultViewFactory.swift
  Sources/StreamChatSwiftUI/ViewFactory.swift
  StreamChatSwiftUITests/Tests/Utils/ViewFactory_Tests.swift
Labels: ✅ Feature

#839 Allow customisation of message previews in lists
  CHANGELOG.md
  Sources/StreamChatSwiftUI/Utils.swift
  Sources/StreamChatSwiftUI/Utils/MessagePreviewFormatter.swift
Labels: ✅ Feature
