Repository GetStream/stream-chat-swiftui, pull requests merged in 2025-04, with the labels that each got.

#806 Add support for editing attachments
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelView.swift
  Sources/StreamChatSwiftUI/ChatChannel/ChatChannelViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/ComposerConfig.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/ComposerModels.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/MessageComposerView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Composer/MessageComposerViewModel.swift
  Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageContainerView.swift
  Sources/StreamChatSwiftUI/ChatChannel/Reactions/MessageActions/DefaultMessageActions.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelViewModel_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageActions_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageComposerView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/MessageContainerView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_editingMessageWithFileAttachment.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_editingMessageWithImageAttachment.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_editingMessageWithText.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_editingMessageWithVideoAttachment.default-light.png
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/MessageComposerView_Tests/test_composerView_editingMessageWithVoiceRecording.default-light.png
Labels: 🐞 Bug, ✅ Feature

#810 Fix translated message showing original text in message actions overlay
  CHANGELOG.md
  Sources/StreamChatSwiftUI/ChatChannel/Reactions/ReactionsOverlayView.swift
  StreamChatSwiftUITests/Tests/ChatChannel/ReactionsOverlayView_Tests.swift
  StreamChatSwiftUITests/Tests/ChatChannel/__Snapshots__/ReactionsOverlayView_Tests/test_reactionsOverlayView_translated.1.png
Labels: 🐞 Bug

#812 [CI] Install an older ipsw version
  .github/actions/setup-ios-runtime/action.yml
  .github/workflows/cron-checks.yml
  Githubfile
  Scripts/bootstrap.sh
Labels: 🤖 CI/CD
